import { convertToBoolean, convertToInteger, convertToNumber, convertToString } from '../src'

describe('convert', function () {
  describe('convertToBoolean', function () {
    it('true ==> true', () => expect(convertToBoolean(true)).toEqual(true))
    it('false ==> false', () => expect(convertToBoolean(false)).toEqual(false))
    test("'True' ==> true", () => expect(convertToBoolean('True')).toEqual(true))
    test("'FaLSe' ==> false", () => expect(convertToBoolean('FaLSe')).toEqual(false))
    it('undefined ==> null', () => expect(convertToBoolean(undefined)).toBeNull())
    it('null ==> null', () => expect(convertToBoolean(null)).toBeNull())
    it('0 ==> null', () => expect(convertToBoolean(0)).toBeNull())
    it('1 ==> null', () => expect(convertToBoolean(1)).toBeNull())
    it('[] ==> null', () => expect(convertToBoolean([])).toBeNull())
    it('{} ==> null', () => expect(convertToBoolean({})).toBeNull())
    test("'' ==> null", () => expect(convertToBoolean('')).toBeNull())
  })

  describe('convertToInteger', function () {
    it('0 ==> 0', () => expect(convertToInteger(0)).toEqual(0))
    it('1 ==> 1', () => expect(convertToInteger(1)).toEqual(1))
    it('123132.23 ==> 123132', () => expect(convertToInteger(123132)).toEqual(123132))
    it('-123132.23 ==> -123132', () => expect(convertToInteger(-123132)).toEqual(-123132))
    test("'0' ==> 0", () => expect(convertToInteger('0')).toEqual(0))
    test("'1' ==> 1", () => expect(convertToInteger('1')).toEqual(1))
    test("'-1' ==> -1", () => expect(convertToInteger('-1')).toEqual(-1))
    test("'1xxx_y' ==> null", () => expect(convertToInteger('1xxx_y')).toBeNull())
    it('true ==> null', () => expect(convertToInteger(true)).toBeNull())
    it('false ==> null', () => expect(convertToInteger(false)).toBeNull())
    it('undefined ==> null', () => expect(convertToInteger(undefined)).toBeNull())
    it('null ==> null', () => expect(convertToInteger(null)).toBeNull())
    it('[] ==> null', () => expect(convertToInteger([])).toBeNull())
    it('{} ==> null', () => expect(convertToInteger({})).toBeNull())
    test("'' ==> null", () => expect(convertToInteger('')).toBeNull())
  })

  describe('convertToNumber', function () {
    it('0 ==> 0', () => expect(convertToNumber(0)).toEqual(0))
    it('1 ==> 1', () => expect(convertToNumber(1)).toEqual(1))
    it('123132.23 ==> 123132.23', () => expect(convertToNumber(123132.23)).toEqual(123132.23))
    it('-123132.23 ==> -123132.23', () => expect(convertToNumber(-123132.23)).toEqual(-123132.23))
    test("'0' ==> 0", () => expect(convertToNumber('0')).toEqual(0))
    test("'1' ==> 1", () => expect(convertToNumber('1')).toEqual(1))
    test("'-1' ==> -1", () => expect(convertToNumber('-1')).toEqual(-1))
    test("'1xxx_y' ==> null", () => expect(convertToNumber('1xxx_y')).toBeNull())
    it('true ==> null', () => expect(convertToNumber(true)).toBeNull())
    it('false ==> null', () => expect(convertToNumber(false)).toBeNull())
    it('undefined ==> null', () => expect(convertToNumber(undefined)).toBeNull())
    it('null ==> null', () => expect(convertToNumber(null)).toBeNull())
    it('[] ==> null', () => expect(convertToNumber([])).toBeNull())
    it('{} ==> null', () => expect(convertToNumber({})).toBeNull())
    test("'' ==> null", () => expect(convertToNumber('')).toBeNull())
  })

  describe('convertToString', function () {
    test("'' ==> ''", () => expect(convertToString('')).toEqual(''))
    test("-1 ==> '-1'", () => expect(convertToString(-1)).toEqual('-1'))
    test("true ==> 'true'", () => expect(convertToString(true)).toEqual('true'))
    test("false ==> 'false'", () => expect(convertToString(false)).toEqual('false'))
    it('undefined ==> null', () => expect(convertToString(undefined)).toBeNull())
    it('null ==> null', () => expect(convertToString(null)).toBeNull())
    it('[] ==> null', () => expect(convertToString([])).toBeNull())
    it('{} ==> null', () => expect(convertToString({})).toBeNull())
  })
})
