export type { RollupTypescriptOptions as TypescriptOptions } from '@rollup/plugin-typescript'
export type { RollupCommonJSOptions as CommonJSOptions } from '@rollup/plugin-commonjs'
export type { RollupJsonOptions as JsonOptions } from '@rollup/plugin-json'
export type { RollupNodeResolveOptions as NodeResolveOptions } from '@rollup/plugin-node-resolve'
export type { Options as DtsOptions } from 'rollup-plugin-dts'
